// Simulated camera contracts, not a live SDK or geographical-accuracy test.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {validFlight,installFlight} from './flight.mjs';import {hostPolicy} from './session.mjs';
const position={lon:126.52155,lat:33.51325,height:700,pitch:-50,heading:0};
function fixture({full=true,terrain=24}={}){const calls=[],messages=[];let handler=null;const camera={flyTo:p=>calls.push(['fallback',p]),lookAtTransform:p=>calls.push(['release',p]),lookAt:(...p)=>calls.push(['orbit',...p]),cancelFlight:()=>calls.push(['cancel'])};if(full)camera.flyToBoundingSphere=(...p)=>calls.push(['fly',...p]);const C={Math:{toRadians:n=>n*Math.PI/180},Cartesian3:{fromDegrees:(...p)=>p},Cartographic:{fromDegrees:(...p)=>p},BoundingSphere:class{constructor(center,radius){this.center=center;this.radius=radius;}},HeadingPitchRange:class{constructor(heading,pitch,range){Object.assign(this,{heading,pitch,range});}},Matrix4:{IDENTITY:'identity'}};const viewer={camera,scene:{globe:{getHeight:()=>terrain},preRender:{addEventListener:f=>{handler=f;return()=>handler=null;}}}};return {controller:installFlight(viewer,C,(...p)=>messages.push(p)),calls,messages,viewer,C,render:()=>handler?.(),get listening(){return !!handler;}};}
test('flight validates coordinates, range, pitch and heading',()=>{assert(validFlight(position));for(const field of ['lon','lat','height','heading'])assert(!validFlight({...position,[field]:NaN}));for(const p of [{lon:127},{lat:34},{height:99},{height:10001},{pitch:-10},{heading:361}])assert(!validFlight({...position,...p}));});
test('all exploration scene positions are within checked camera bounds',()=>{const s=fs.readFileSync(new URL('explore.mjs',import.meta.url),'utf8');const scenes=vm.runInNewContext(s.match(/Object.freeze\((\[[\s\S]*?\])\);/)[1]);assert.equal(scenes.length,6);assert(scenes.every(validFlight));});
test('camera uses a target-centered oblique view and observed ground height',()=>{const f=fixture();assert(f.controller.fly(position));assert.equal(f.calls[0][0],'fly');assert.equal(f.calls[0][1].center[2],24);assert.equal(f.calls[0][2].offset.range,700);assert.equal(f.calls[0][2].offset.pitch,-50*Math.PI/180);});
test('unavailable terrain only changes camera anchor, never generates geometry',()=>{const f=fixture({terrain:undefined});f.controller.fly(position);assert.equal(f.calls[0][1].center[2],24);const g=fixture({terrain:NaN});g.controller.fly(position);assert.equal(g.calls[0][1].center[2],0);assert(!('entities' in g.viewer));});
test('camera has a reduced-SDK fallback without adding buildings',()=>{const f=fixture({full:false});f.controller.fly(position);assert.equal(f.calls[0][0],'fallback');});
test('invalid movement does not alter the existing camera',()=>{const f=fixture();assert.equal(f.controller.fly({...position,lon:127}),false);assert.equal(f.calls.length,0);});
test('orbit is removed and camera reference released on stop',()=>{const f=fixture();f.controller.fly(position);f.controller.orbit(true);assert(f.listening);f.render();assert(f.calls.some(c=>c[0]==='orbit'));f.controller.stop();assert(!f.listening);assert(f.calls.some(c=>c[0]==='release'));});
test('switching scene clears the old orbit listener',()=>{const f=fixture();f.controller.fly(position);f.controller.orbit(true);f.controller.fly({...position,height:900});assert(!f.listening);});
test('unsupported auto orbit reports unavailable rather than claiming success',()=>{const f=fixture();f.controller.orbit(true);assert(f.messages.some(m=>m[0]==='flight-unavailable'));assert(!f.listening);});
test('exact owned explorer allowed, shared hosts and other projects blocked',()=>{assert(hostPolicy('https://kokoom94-ai.github.io/jeju-oldtown-3d/explore.html').canConnect);for(const u of ['https://rawcdn.githack.com/kokoom94-ai/jeju-oldtown-3d/commit/explore.html','https://kokoom94-ai.github.io/jeju-now-981/explore.html','https://kokoom94-ai.github.io/jeju-oldtown-3d/evil/explore.html'])assert(!hostPolicy(u).canConnect);});
test('new explorer does not store key or automatically request SDK',()=>{const js=fs.readFileSync(new URL('explore.mjs',import.meta.url),'utf8'),html=fs.readFileSync(new URL('explore.html',import.meta.url),'utf8');assert(!/localStorage|sessionStorage|indexedDB/.test(js));assert(!html.includes('webglMapInit'));assert(js.includes("if(!policy.canConnect)throw"));assert(js.includes("$('#api-key').value='';"));assert(js.includes('productionReady:false,walkingEnabled:false'));});
test('legacy aerial derivative has a mandatory unique hook, standalone source untouched',()=>{const build=fs.readFileSync(new URL('prepare.mjs',import.meta.url),'utf8'),entry=fs.readFileSync(new URL('../realism/entry.js',import.meta.url),'utf8');assert(build.includes("entry.split(marker).length!==2"));assert(build.includes("'flight-entry.js'"));assert(!entry.includes('jeju-osm-preview-v1'));});
test('preview control messages validate both source and origin and block walking',()=>{const s=fs.readFileSync(new URL('preview-hook.js',import.meta.url),'utf8');assert(s.includes("e.source!==parent||e.origin!==origin"));assert(s.includes("e.stopImmediatePropagation()"));assert(s.includes("setMode('overview')"));assert(s.includes("r.avatar.visible=false"));assert(s.includes("p.lon<126.462"));});
