import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {CHECKPOINTS,recordPhase,cameraPosition,environmentProbe} from './inspection.mjs';
const seed=JSON.parse(fs.readFileSync(new URL('places.json',import.meta.url),'utf8'));
test('five requested checkpoints reuse draft seed coordinates',()=>{assert.equal(CHECKPOINTS.length,5);for(const p of CHECKPOINTS){const q=seed.find(q=>q.id===p.id);assert.equal(p.lon,q.lon);assert.equal(p.lat,q.lat);}});
test('camera angles are explicit and no walk mode is available',()=>{assert.equal(cameraPosition('gwandeok').pitch,-50);assert.equal(cameraPosition('cju','overhead').pitch,-90);assert.throws(()=>cameraPosition('cju','walk'));assert.throws(()=>cameraPosition('unknown'));});
test('timeline accepts only bounded enum events, never arbitrary messages',()=>{const log=recordPhase([],'script-loaded',1000);assert.deepEqual(log,[{phase:'script-loaded',at:'1970-01-01T00:00:01.000Z'}]);assert.equal(recordPhase(log,'apiKey=PRIVATE'),log);assert.equal(recordPhase(log,'error',NaN),log);assert.equal(recordPhase(log,'error',1e30),log);});
test('timeline is bounded to twenty recent events',()=>{let log=[];for(let i=0;i<50;i++)log=recordPhase(log,'error',i);assert.equal(log.length,20);});
test('WebGL 2 probe releases temporary context and never certifies geometry',()=>{let released=0;const d={createElement:()=>({getContext:()=>({getExtension:()=>({loseContext:()=>released++})})})};const r=environmentProbe({isSecureContext:true,fetch(){},crypto:{subtle:{digest(){}}}},d);assert.equal(r.webgl,2);assert.equal(released,1);assert.equal(r.geometryVerified,false);assert.equal(r.secureContext,true);});
test('WebGL 1 fallback and unavailable graphics are distinguished',()=>{const d={createElement:()=>({getContext:name=>name==='webgl'?{getExtension:()=>null}:null})};assert.equal(environmentProbe({},d).webgl,1);assert.equal(environmentProbe({},{createElement:()=>{throw Error('fixture');}}).webgl,0);});
