const fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {pathToFileURL}=require('node:url');
const {chromium}=require(path.join(process.env.PLAYWRIGHT_ROOT,'node_modules/playwright'));
const checks=[],errors=[],blocked=[];let browser,staticServer,proxy,slowServer,failure=null;
const record=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',r));
(async()=>{try{
 const root=path.resolve('_precision_site');
 staticServer=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost');const f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':decodeURIComponent(u.pathname)));if(!f.startsWith(root+path.sep))throw Error();res.writeHead(200,{'Content-Type':{'.html':'text/html; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json'}[path.extname(f)]||'text/plain'});res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
 await listen(staticServer);const pageURL='http://127.0.0.1:'+staticServer.address().port+'/connect.html';
 // A registered service URL is the site base, not the diagnostic document path.
 const registeredURL=new URL('./',pageURL).href;
 const {createProxyServer}=await import(pathToFileURL(path.resolve('precision/proxy-server.mjs')));
 let upstreamCalls=0;proxy=createProxyServer({registeredUrl:registeredURL,fetchImpl:async()=>{upstreamCalls++;throw Error('Unexpected upstream');}});await listen(proxy.server);
 const proxyURL='http://127.0.0.1:'+proxy.server.address().port;
 slowServer=http.createServer((req,res)=>{setTimeout(()=>{if(res.destroyed)return;res.writeHead(200,{'Access-Control-Allow-Origin':new URL(pageURL).origin,'Content-Type':'application/json'});res.end(JSON.stringify({provider:'VWorld WebGL 3.0',transport:'sdk-bootstrap-proxy',serviceUrl:registeredURL,keyConfigured:false,sdkPath:'/api/vworld/sdk.js'}));},600);});await listen(slowServer);
 const executable=['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium'].find(f=>fs.existsSync(f));
 browser=await chromium.launch({...(executable?{executablePath:executable}:{}),headless:true,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='vworld.kr'||u.hostname.endsWith('.vworld.kr')){blocked.push(u.hostname);return route.abort();}return route.continue();});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(String(e)));await p.goto(pageURL);
 await p.waitForFunction('window.__JEJU_PRECISION__?.placeCount===32');
 record('Local direct mode starts with no provider connection',await p.evaluate('!window.__JEJU_PRECISION__.status.sdkReady'));
 await p.locator('#api-key').fill('TEST-ONLY-NOT-A-REAL-KEY-00000');await p.locator('#connection-mode').selectOption('proxy');
 record('Proxy mode clears and disables browser key input',await p.locator('#api-key').inputValue()===''&&await p.locator('#api-key').isDisabled());
 await p.locator('#proxy-url').fill(proxyURL);await p.locator('#confirmed').check();await p.locator('#connect').click();
 await p.waitForFunction("window.__JEJU_PRECISION__.status.state==='error'");
 record('Real unconfigured proxy reports missing environment key',(await p.locator('#notice').innerText()).includes('VWORLD_API_KEY'));
 record('Preflight error leaves provider iframe absent',await p.locator('#frame').isHidden());
 record('Missing key does not contact provider',upstreamCalls===0&&blocked.length===0);
 record('Diagnostic records proxy and sanitized preflight failure',await p.evaluate("window.__JEJU_PRECISION__.report.transport==='sdk-bootstrap-proxy'&&window.__JEJU_PRECISION__.report.failureCode==='PREFLIGHT_FAILED'&&!window.__JEJU_PRECISION__.report.productionReady"));
 await p.locator('#proxy-url').fill('http://127.0.0.1:'+slowServer.address().port);await p.locator('#connect').click();await p.locator('#disconnect').click();await p.waitForTimeout(800);
 record('Cancelled preflight cannot change disconnected state later',await p.evaluate("window.__JEJU_PRECISION__.status.state==='not-configured'"));
 await p.locator('#connection-mode').selectOption('direct');await p.locator('#api-key').fill('TEST-ONLY-NOT-A-REAL-KEY-00000');await p.locator('#connect').click();
 await p.waitForFunction("window.__JEJU_PRECISION__.status.state==='error'");
 record('Intentionally blocked SDK reports a network failure, not success',await p.evaluate("window.__JEJU_PRECISION__.report.failureCode==='SDK_NETWORK_FAILED'&&!window.__JEJU_PRECISION__.status.sdkReady"));
 record('Test credential cleared after failure',await p.locator('#api-key').inputValue()==='');
 record('No credential written to browser storage or diagnostic',await p.evaluate("localStorage.length===0&&sessionStorage.length===0&&!JSON.stringify(window.__JEJU_PRECISION__.report).includes('TEST-ONLY')"));
 await p.locator('#connection-mode').selectOption('proxy');
 fs.mkdirSync('precision-qa',{recursive:true});await p.screenshot({path:'precision-qa/proxy-desktop.png',fullPage:true});
 await p.setViewportSize({width:390,height:844});
 record('Proxy form has no mobile horizontal overflow',await p.evaluate('document.documentElement.scrollWidth<=innerWidth'));
 await p.screenshot({path:'precision-qa/proxy-mobile.png',fullPage:true});
 record('All provider traffic blocked locally, no real SDK or geometry tested',blocked.length===1&&upstreamCalls===0);
 record('No unexpected browser JavaScript errors',errors.length===0);
 await context.close();
}catch(e){failure=String(e);}finally{
 if(browser)await browser.close();
 for(const s of [staticServer,proxy?.server,slowServer])if(s)await new Promise(r=>{s.closeAllConnections();s.close(r);});
}
const result={checkedAt:new Date().toISOString(),runId:process.env.GITHUB_RUN_ID,ok:!failure,passed:checks.filter(c=>c.passed).length,checks,errors,failure,providerRequestsAllowed:0,providerRequestsIntentionallyBlocked:blocked.length,sdkLiveTested:false,jejuPrecisionModelsReceived:false,productionReady:false,scope:'Local HTTP proxy preflight and browser failure/cancellation checks. No successful SDK or model response is simulated.'};
fs.mkdirSync('precision-qa',{recursive:true});fs.writeFileSync('precision/proxy-browser-result.json',JSON.stringify(result,null,2));fs.writeFileSync('precision-qa/proxy-browser-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(!result.ok)process.exitCode=1;
})();
