import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {errorText,connectionReport,cleanSDKDiagnostic} from './sdk-diagnostics.mjs';
test('error summary exports only bounded enums and capability booleans',()=>{const r=connectionReport({failureCode:'SDK_NETWORK_FAILED',diagnostic:{stage:'map-configure',exceptionName:'TypeError',key:'TEST-SECRET',message:'TEST-SECRET',url:'https://provider/?key=TEST-SECRET',webgl:2,viewer:true},timeline:['script-loaded','TEST-SECRET']});assert.equal(r.failureCode,'SDK_NETWORK_FAILED');assert.deepEqual(r.timeline,['script-loaded']);assert(!JSON.stringify(r).includes('TEST-SECRET'));assert(!r.geometryVerified);assert(!r.productionReady);});
test('unknown error is not displayed verbatim',()=>{const text=errorText('TEST-SECRET');assert(text.includes('SDK_INIT_FAILED'));assert(!text.includes('TEST-SECRET'));});
test('unknown stages and exception messages are discarded',()=>{const d=cleanSDKDiagnostic({stage:'https://evil/?key=SECRET',exceptionName:'SECRET',webgl:99});assert.equal(d.stage,null);assert.equal(d.exceptionName,null);assert.equal(d.webgl,null);});
test('official adapter retains parser-inserted script and uses no user key storage',()=>{const frame=fs.readFileSync('precision/sdk-frame.mjs','utf8');assert(frame.includes('document.open();document.write(html);document.close()'));assert(frame.includes("e.source!==parent||e.origin!==origin"));assert(!/localStorage|sessionStorage/.test(frame));});
test('actual iframe page replaces srcdoc on both active connection screens',()=>{for(const p of ['precision/explore.mjs','precision/app.mjs']){const s=fs.readFileSync(p,'utf8');assert(s.includes('mountSDKFrame('));assert(!/\.srcdoc\s*=/.test(s));}});
test('frame host sends no html until exact frame source URL and nonce are checked',()=>{const s=fs.readFileSync('precision/sdk-frame-host.mjs','utf8');assert(s.includes('frame.contentWindow.location.href!==target.href'));assert(s.includes('e.origin!==location.origin'));assert(s.includes("pending=''"));assert(s.includes('FRAME_LOAD_FAILED'));assert(s.includes('12000'));});
test('bootstrap guards are self-contained and never copy raw messages into reports',()=>{const s=fs.readFileSync('precision/sdk-guard.mjs','utf8');assert(s.includes("fail(classify(String(message),'PROVIDER_NOTICE'))"));assert(s.includes('exceptionName'));assert(!s.includes('message:message'));assert(!s.includes('message:e.message'));});
