import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {hostPolicy,TARGETS,createObservations,cleanObject,cleanProperties,addObservation,diagnostics} from './session.mjs';
import {initialState,transition} from './bridge.mjs';
const object={providerType:'Cesium3DTileFeature',lon:126.527,lat:33.512,properties:[['name','test fixture']]};
test('shared CDN cannot accept a provider key',()=>assert.equal(hostPolicy('https://rawcdn.githack.com/a/b').canConnect,false));
test('similarly named hostile origins are rejected',()=>assert.equal(hostPolicy('https://kokoom94-ai.github.io.evil.example').canConnect,false));
test('dedicated GitHub Pages origin allowed',()=>assert.equal(hostPolicy('https://kokoom94-ai.github.io/jeju-oldtown-3d/').canConnect,true));
test('old Netlify host is not trusted by the new app',()=>assert.equal(hostPolicy('https://jeju-before-walk.netlify.app').canConnect,false));
test('unrecognized HTTPS origins fail closed',()=>assert.equal(hostPolicy('https://example.com').canConnect,false));
test('HTTP public hosting is rejected',()=>assert.equal(hostPolicy('http://kokoom94-ai.github.io').canConnect,false));
test('local testing allowed',()=>assert.equal(hostPolicy('http://127.0.0.1:4321').mode,'local-test'));
test('file and invalid URLs cannot request provider',()=>{assert.equal(hostPolicy('file:///index.html').canConnect,false);assert.equal(hostPolicy('invalid').canConnect,false);});
test('all requested named area targets present',()=>assert.deepEqual(TARGETS.map(t=>t.name),['일도동','이도동','건입동','삼도동','용담동','제주공항 일대']));
test('all observations initially uninspected',()=>assert(Object.values(createObservations()).every(x=>x.status==='not-inspected'&&x.object===null)));
test('no inferred object without provider type',()=>assert.equal(cleanObject({lon:126.52,lat:33.51}),null));
test('out-of-scope source object rejected',()=>assert.equal(cleanObject({...object,lon:127}),null));
test('coordinates absent cannot be recorded',()=>assert.throws(()=>addObservation(createObservations(),'ildo',{...object,lon:null,lat:null})));
test('far-away target cannot be certified by unrelated selection',()=>assert.throws(()=>addObservation(createObservations(),'airport',object)));
test('record is an observation, never a geometry certificate',()=>{const r=addObservation(createObservations(),'ildo',object);assert.equal(r.ildo.status,'sample-observed-not-validated');assert.equal(r.ildo.object.heightVerified,false);assert.equal(r.ildo.object.shapeVerified,false);});
test('invalid target or timestamp rejected',()=>{assert.throws(()=>addObservation(createObservations(),'unknown',object));assert.throws(()=>addObservation(createObservations(),'ildo',object,'not-a-date'));});
test('provider secret-like properties removed',()=>assert.deepEqual(cleanProperties([['apikey','x'],['Authorization','x'],['secret','x'],['name','safe']]),[['name','safe']]));
test('diagnostic never copies arbitrary state fields',()=>{const s={...initialState(),apiKey:'DO-NOT-EXPORT',secret:'DO-NOT-EXPORT',productionReady:true};const r=diagnostics(s,createObservations(),'https://kokoom94-ai.github.io',32);assert.equal(r.productionReady,false);assert(!JSON.stringify(r).includes('DO-NOT-EXPORT'));});
test('SDK initialized is not all-area coverage',()=>{const r=diagnostics(transition(initialState(),'sdk-ready'),createObservations(),'https://kokoom94-ai.github.io',32);assert.equal(r.sdkReady,true);assert.equal(r.regionBoundaryCoverageVerified,false);assert.equal(r.heightAccuracyVerified,false);assert.equal(r.sourceDate,null);});
test('six synthetic test observations do not change truth flags',()=>{let log=createObservations();for(const t of TARGETS)log=addObservation(log,t.id,{...object,lon:t.lon,lat:t.lat});const r=diagnostics(initialState(),log,'https://kokoom94-ai.github.io',32);assert.equal(r.observations.length,6);assert.equal(r.productionReady,false);assert.equal(r.roofShapeVerified,false);assert.equal(r.walkingCollisionVerified,false);});
test('app has no key persistence or image-generated buildings',()=>{const app=fs.readFileSync(new URL('./app.mjs',import.meta.url),'utf8');assert(!/localStorage|sessionStorage|BoxGeometry|extrudedHeight/.test(app));assert(app.includes("if(!policy.canConnect)throw Error"));});

test('another Pages project cannot enter a key',()=>{for(const url of ['https://kokoom94-ai.github.io/jeju-now-981/','https://kokoom94-ai.github.io/jeju-oldtown-3d-evil/','https://kokoom94-ai.github.io/'])assert.equal(hostPolicy(url).canConnect,false);});
