import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {installNavigation} from './navigation.mjs';import {createWalkGuard} from './walk-guard.mjs';import {parsePublicConnection,loadPublicConnection,PUBLIC_SERVICE_URL} from './public-connection.mjs';import {frameHTML} from './bridge.mjs';
function element(){const handlers={};return {style:{touchAction:'auto'},clientHeight:900,addEventListener(n,f){(handlers[n]??=[]).push(f);},removeEventListener(n,f){handlers[n]=(handlers[n]||[]).filter(x=>x!==f);},emit(n,e={}){for(const f of handlers[n]||[])f({preventDefault(){},pointerId:1,button:0,clientX:600,clientY:500,...e});},focus(){},setPointerCapture(){},get count(){return Object.values(handlers).flat().length;}};}
function fixture(){const canvas=element(),win=element(),calls=[],C={HeadingPitchRange:class{constructor(heading,pitch,range){Object.assign(this,{heading,pitch,range});}},Cartographic:{fromDegrees:(...p)=>p},Cartesian3:{fromDegrees:(...p)=>p},Math:{toRadians:x=>x*Math.PI/180},Matrix4:{IDENTITY:'identity'}};const viewer={scene:{canvas,globe:{getHeight:()=>25},screenSpaceCameraController:{enableInputs:true},requestRender(){}},camera:{lookAt:(...p)=>calls.push(p),lookAtTransform(){},cancelFlight(){}}};const ctx={viewer,C,window:win,document:{hidden:false},performance:{now:()=>100},send(){},Map,Math,requestAnimationFrame:()=>1,cancelAnimationFrame(){}};vm.runInNewContext('this.nav=('+installNavigation.toString()+')(viewer,C,send)',ctx);return {nav:ctx.nav,canvas,win,viewer,calls};}
test('actual pointer deltas update heading tilt and camera calls',()=>{const f=fixture();f.canvas.emit('pointerdown');f.canvas.emit('pointermove',{clientX:300,clientY:600});assert(f.nav.state.heading>90);assert.notEqual(f.nav.state.pitch,-50);assert(f.calls.length);});
test('orbit wraps beyond 360 without locking at a full revolution',()=>{const f=fixture();for(let i=0;i<5;i++){f.canvas.emit('pointerdown');f.canvas.emit('pointermove',{clientX:300});f.canvas.emit('pointerup');}assert(Math.abs(f.nav.state.heading-150)<.01);});
test('right drag pans instead of rotating; wheel zoom stays bounded',()=>{const f=fixture(),s=f.nav.state;f.canvas.emit('pointerdown',{button:2});f.canvas.emit('pointermove',{clientX:450,clientY:550});assert.notEqual(f.nav.state.lon,s.lon);assert.equal(f.nav.state.heading,s.heading);f.canvas.emit('wheel',{deltaY:-800});assert(f.nav.state.height<700);});
test('button zoom and angle preserve freely dragged heading',()=>{const f=fixture();f.canvas.emit('pointerdown');f.canvas.emit('pointermove',{clientX:400});f.canvas.emit('pointerup');const h=f.nav.state.heading;f.nav.zoom(1);f.nav.angle(-25);assert.equal(f.nav.state.heading,h);assert.equal(f.nav.state.pitch,-25);f.nav.north();assert.equal(f.nav.state.heading,0);});
test('two finger pinch and twist update camera',()=>{const f=fixture();f.canvas.emit('pointerdown',{pointerId:1,clientX:400});f.canvas.emit('pointerdown',{pointerId:2,clientX:600});f.canvas.emit('pointermove',{pointerId:2,clientX:700,clientY:550});assert(f.nav.state.height<700);assert.notEqual(f.nav.state.heading,0);});
test('street mode suspends gestures and destroy restores native inputs',()=>{const f=fixture();f.nav.setEnabled(false);f.canvas.emit('pointerdown');f.canvas.emit('pointermove',{clientX:200});assert.equal(f.calls.length,0);f.nav.destroy();assert.equal(f.canvas.count,0);assert.equal(f.win.count,0);assert.equal(f.viewer.scene.screenSpaceCameraController.enableInputs,true);});
const pathData={schema:1,paths:[{highway:'footway',bridge:false,tunnel:false,layer:0,coords:[[126.522,33.513],[126.523,33.513]]}],buildings:[]};
test('airport and west-coast walking are excluded',()=>{const g=createWalkGuard(pathData);assert(g.allowed([126.5225,33.513]));assert(!g.allowed([126.491,33.507]));assert(!g.allowed([126.512,33.516]));});
test('vehicle roads bridge tunnel steps and raised layers are excluded',()=>{for(const change of [{highway:'secondary'},{highway:'steps'},{bridge:true},{tunnel:true},{layer:1}])assert.equal(createWalkGuard({...pathData,paths:[{...pathData.paths[0],...change}]}).segmentCount,0);});
test('building footprint blocks passage and long teleport is refused',()=>{const g=createWalkGuard({...pathData,buildings:[[[126.52249,33.51299],[126.52251,33.51299],[126.52251,33.51301],[126.52249,33.51301]]]});assert(g.blocked([126.5225,33.513]));assert(!g.sweep([126.52246,33.513],[126.52254,33.513]));assert(!g.sweep([126.5221,33.513],[126.5229,33.513]));});
const key='TEST-ONLY-NOT-A-REAL-KEY-00000',cfg={schema:1,enabled:true,browserVisibleKey:true,serviceUrl:PUBLIC_SERVICE_URL,apiKey:key};
test('public configuration validates exact service and visibility',()=>{assert(parsePublicConnection(cfg).enabled);assert.throws(()=>parsePublicConnection({...cfg,browserVisibleKey:false}));assert.throws(()=>parsePublicConnection({...cfg,serviceUrl:'https://evil.test/'}));assert.deepEqual(parsePublicConnection({...cfg,enabled:false}),{enabled:false});});
test('shared CDN does not fetch public key',async()=>{let calls=0;assert(!(await loadPublicConnection('https://rawcdn.githack.com/file/index.html',()=>calls++)).enabled);assert.equal(calls,0);});
test('public configuration body is bounded and redirects disallowed',async()=>{const fetcher=async(url,opt)=>{assert.equal(opt.redirect,'error');assert.equal(opt.cache,'no-store');return new Response(JSON.stringify(cfg),{headers:{'Content-Type':'application/json'}});};assert((await loadPublicConnection(PUBLIC_SERVICE_URL,fetcher)).enabled);await assert.rejects(()=>loadPublicConnection(PUBLIC_SERVICE_URL,async()=>new Response('x'.repeat(5000),{headers:{'Content-Type':'application/json'}})));});
test('serialized SDK frame contains independent navigation and walk controllers',()=>{const html=frameHTML({key,channel:'test-channel-00000',origin:'https://kokoom94-ai.github.io'}),js=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1];new vm.Script(js);assert(js.includes('const installNavigation='));assert(js.includes('const installWalk='));assert(js.includes('const createWalkGuard='));});
