import fs from 'node:fs/promises';
const original=await fs.readFile('index.html','utf8');
const map=JSON.parse(await fs.readFile('realism/world-v2.json','utf8'));
const materials=JSON.parse(await fs.readFile('realism/acquisition.json','utf8'));
if(map.mode!=='osm'||map.roads.length<100||map.buildings.length<100||!materials.materialsComplete)throw Error('Real geometry or photo materials unavailable: publication blocked');
const oldData=JSON.parse(original.match(/globalThis\.JEJU_DATA=(.+);\n/)[1]);
const core=original.slice(original.indexOf('/* JEJU BEFORE · navigation'),original.indexOf('/* Shared OSM converter'));
const osm=original.slice(original.indexOf('/* Shared OSM converter'),original.indexOf('/* JEJU BEFORE · small, original WebGL'));
let app=original.slice(original.indexOf('/* JEJU BEFORE · application'),original.lastIndexOf('</script>'));
app=app.replace(/async function serverStatus\(\)\{.*\}\n/,'async function serverStatus(){state.naverConfigured=false;}\n');
app=app.replaceAll("mode==='walk'?19:760","mode==='walk'?12:630").replace("mode==='walk'?.36:.83","mode==='walk'?.24:.62");
app=app.replace('innerWidth<680?1200:1050','innerWidth<680?980:850').replace('state.renderer.pitch=.91','state.renderer.pitch=.65');
app=app.replace("$('#data-status span').textContent='OSM 적용'","$('#data-status span').textContent='실제 윤곽 · 외관 연출'");
app=app.replaceAll('OSM 기반 · 외관·경로·장소 검증 전','OSM 윤곽 · 외관·높이·보행 조건 미검증');
app=app.replace('OpenStreetMap에서 내려받은 도로·건물 원본이 적용되었습니다. 건물 외관과 높이 일부는 단순화되어 있으며 지형 고도·현장 보행 조건과 기본 장소 좌표는 검증 전입니다.','도로·건물 윤곽과 해안선은 OpenStreetMap 원본입니다. 대부분의 높이는 9m 가정값이며, 층수 제공 건물은 층당 3m로 환산했습니다. 사진 재질은 Poly Haven의 일반 표면 스캔으로 제주 현장사진이 아닙니다. 창문·옥상 장치·수목 크기·빛·차선 표현은 시각화입니다. 지형 고도·현장 보행 조건·출입구는 검증 전입니다.');
app=app.replace('setTimeout(init,60);',`setTimeout(()=>{init();const b=document.querySelector('#load-osm');b.disabled=true;b.textContent='실제 OSM 데이터 적용됨';document.querySelector('#osm-load-message').textContent='수신 '+map.capturedAt+' · 건물 '+map.buildings.length.toLocaleString()+'개 / 도로 '+map.roads.length.toLocaleString()+'개';},60);`);
let html=original.slice(0,original.indexOf('<script>'))+original.slice(original.lastIndexOf('</script>')+9);
html=html.replace('<body>','<body class="real-v2">').replace('<title>JEJU:BEFORE — 제주를, 먼저 걸어보다</title>','<title>JEJU:BEFORE 2.0 — 실제 도시 윤곽으로 미리 걷는 제주</title>');
html=html.replace('JEJU OLD TOWN · 3D WALK','REAL GEOMETRY · CINEMATIC CITY').replace('골목의 분위기부터 여행의 동선까지.<br>나의 캐릭터로 시작하는 사전 산책.','실제 도시의 윤곽 위로, 새로운 빛과 질감.<br>현장사진이 아닌 3D 사전 체험.');
html=html.replace('3D 체험 공간을 준비합니다.','실제 도로·건물 원본과 사진 재질을 준비합니다.');
html=html.replace('<div id="districts"',`<div class="real-controls" aria-label="배경 표현 설정"><span class="real-edition">CITY EDITION / 02</span><div class="real-lights" role="group" aria-label="연출용 조명 프리셋"><button data-light="day" class="active">낮</button><button data-light="golden">노을</button><button data-light="blue">블루아워</button></div><button id="real-quality">고화질</button><button id="real-cinema" aria-label="장소 패널 숨기기 또는 표시">화면 몰입</button><small id="real-status">실제 공간 데이터 · 재질 연출</small></div><div id="districts"`);
html=html.replace('공개 OSM 원본 서버에서 이 범위의 도로·건물을 요청합니다. 네트워크 연결이 필요하며 1~3분 걸릴 수 있습니다. 실패하면 현재 초안을 유지합니다. 네이버 원본이나 실측 외벽 모델이 아닙니다.','실제 OSM 스냅샷을 미리 적용한 배포본입니다. 방문할 때마다 원본 서버를 조회하지 않습니다. 네이버 지도·항공사진·거리뷰를 복제하지 않았습니다.');
html=html.replace('<h3>공간 데이터 상태</h3>','<h3>배경 표현과 출처</h3><p>낮·노을·블루아워는 감상용 조명 프리셋이며 실시간 날씨가 아닙니다. 건물 외관과 창문은 실제 촬영 이미지가 아닌 일반 재질로 표현합니다. 실제 거리뷰·위성영상·사진측량 3D는 미연결입니다.</p><p><a href="./realism/LICENSES.txt" target="_blank" rel="noopener noreferrer">데이터·재질 출처 보기</a> · <a href="./realism/world-v2.json" target="_blank" rel="noopener noreferrer">OSM 파생 데이터 (ODbL)</a></p><h3>공간 데이터 상태</h3>');
const css=`
.real-controls{position:absolute;right:82px;top:20px;z-index:8;display:flex;align-items:center;gap:8px;flex-wrap:wrap;max-width:470px;padding:11px 13px;border:1px solid #ffffff22;background:#132529eb;backdrop-filter:blur(18px);border-radius:14px;box-shadow:0 8px 36px #0002;color:#e4ebe5}.real-edition{font-size:9px;letter-spacing:1.7px;color:#bdd98a;margin-right:4px}.real-controls button{border:1px solid #ffffff18;border-radius:7px;background:transparent;color:#cad8ce;padding:7px 9px;font-size:11px;cursor:pointer}.real-lights{display:flex;gap:2px;background:#0d1a1e;border-radius:8px;padding:2px}.real-lights button{border:0}.real-lights button.active{background:#d7f58a;color:#172824}.real-controls small{width:100%;font-size:9px;color:#a6b8b2;letter-spacing:.35px}.real-v2 #intro{color:#f5f3e9;text-shadow:0 2px 18px #071a20a0;pointer-events:none}.real-v2 #intro h1{color:#fffef4;font-size:36px;line-height:1.16}.real-v2 #intro p{color:#e0e9df;line-height:1.7}.real-v2 #intro .eyebrow{color:#e3f2d5}.real-v2 #stage:after{content:'';pointer-events:none;position:absolute;inset:0;background:linear-gradient(110deg,#10202b33 0%,transparent 38%);z-index:0}.real-v2 #map-labels{z-index:3}.real-v2 #intro,.real-v2 #districts{z-index:4}.real-v2 .map-disclaimer{background:#14262bd9;color:#c9d8cd;z-index:8}.real-v2 .map-disclaimer button{color:#d1decd}.real-v2 .map-disclaimer a{color:#c5d9d7}.real-v2 #intro{top:100px}.real-v2 #districts{top:292px}.real-v2 #world{background:#9fb9c9}.real-v2 #real-cinema{min-width:60px}.real-v2.cinema #sidebar{display:none}.real-v2.cinema #stage{right:0}.real-v2.cinema #intro{opacity:0}.real-v2.cinema #districts{top:88px}.real-v2.cinema .topnav{opacity:.45}.real-v2.walk-view #intro{display:none}.real-v2.walk-view #districts{top:98px}
@media(max-width:1100px){.real-controls{right:75px;max-width:310px}.real-edition{display:none}.real-v2 #intro h1{font-size:30px}.real-v2 #intro{top:102px}.real-v2 #districts{top:285px}}
@media(max-width:680px){.real-controls{top:12px;left:12px;right:66px;max-width:none;padding:7px 9px;gap:5px;border-radius:11px}.real-controls button{padding:6px 8px;font-size:10px}.real-controls small{font-size:8px}.real-v2 #intro{top:100px;left:20px}.real-v2 #intro h1{font-size:27px}.real-v2 #intro p{font-size:10px}.real-v2 #intro .eyebrow{font-size:8px}.real-v2 #districts,.real-v2.walk-view #districts{top:246px;left:12px;right:12px;gap:3px}.real-v2.walk-view #districts,.real-v2.cinema #districts{top:98px}.real-v2 #districts button{font-size:10px;padding:7px 8px}.real-v2 .quality-pill span{font-size:8px}.real-v2 #real-cinema{display:none}.real-v2 .map-disclaimer{display:flex;gap:5px}.real-v2 .map-disclaimer button{font-size:8px;max-width:53%;text-align:left}.real-v2 #osm-credit{font-size:7px}.real-v2 #sidebar.mobile-open{z-index:30}.real-v2.cinema #sidebar{display:block}}
`;
html=html.replace('</head>',`<style>${css}</style><script type="importmap">{"imports":{"three":"./realism/vendor/three.module.js"}}</script></head>`);
const entry=`import * as THREE from './vendor/three.module.js';\nimport {Sky} from './vendor/Sky.js';\nglobalThis.THREE=THREE;globalThis.JejuSky=Sky;\ntry{\nconst data=await fetch(new URL('./world-v2.json',import.meta.url));if(!data.ok)throw Error('실제 공간 원본을 불러오지 못했습니다.');const map=await data.json();if(map.mode!=='osm')throw Error('검증된 형식의 OSM 원본이 아닙니다.');\nglobalThis.JEJU_DATA={map,places:${JSON.stringify(oldData.places).replaceAll('<','\\u003c')}};globalThis.JEJU_MATERIALS=${JSON.stringify(materials.textures)};\n${core}\n${osm}\n${await fs.readFile('realism/renderer.js','utf8')}\n${await fs.readFile('realism/presentation.js','utf8')}\n${app}\n}catch(e){document.querySelector('#loading').hidden=true;document.querySelector('#fatal').hidden=false;document.querySelector('#fatal p').textContent=e.message;document.querySelector('#fatal small').textContent='연결을 확인하고 새로고침해 주세요. 이전 초안으로 자동 대체하지 않습니다.';document.querySelector('#retry').onclick=()=>location.reload();console.error(e);}\n`;
html=html.replace('</body>','<script type="module" src="./realism/entry.js"></script></body>');
await fs.writeFile('realism/entry.js',entry);await fs.writeFile('real.html',html);
console.log(JSON.stringify({ok:true,mapMode:map.mode,roads:map.roads.length,buildings:map.buildings.length,materials:materials.textures.length,htmlBytes:Buffer.byteLength(html),entryBytes:Buffer.byteLength(entry)},null,2));
