/* JEJU BEFORE v2. Actual OSM footprints; generic CC0 surfaces and authored visual details. */
(function(root){
'use strict';
const T=root.THREE,C=root.JejuCore,{geo,dist,clamp,hash,rng,pointInPolygon}=C;
const col=x=>new T.Color(x),V=(x,y,z)=>new T.Vector3(x,y,z);
const palettes=['#c8c3b8','#c8c9c7','#c0b7a3','#d1cdc4','#b6bdba','#afafa8','#cbc6b7'];
class Batch{
 constructor(){this.p=[];this.n=[];this.uv=[];this.c=[];}
 tri(a,b,c,color='#ffffff',uv=[[0,0],[1,0],[1,1]],normal){const n=normal||new T.Vector3().subVectors(V(...b),V(...a)).cross(new T.Vector3().subVectors(V(...c),V(...a))).normalize().toArray();const co=typeof color==='string'?col(color):color;for(let i=0;i<3;i++){this.p.push(...[a,b,c][i]);this.n.push(...n);this.uv.push(...uv[i]);this.c.push(co.r,co.g,co.b);}}
 quad(a,b,c,d,color,uv=[[0,0],[1,0],[1,1],[0,1]],n){this.tri(a,b,c,color,[uv[0],uv[1],uv[2]],n);this.tri(a,c,d,color,[uv[0],uv[2],uv[3]],n);}
 flat(poly,y,color,scale=4){if(poly.length>2&&dist(poly[0],poly.at(-1))<.01)poly=poly.slice(0,-1);if(poly.length<3)return;for(const t of T.ShapeUtils.triangulateShape(poly.map(p=>new T.Vector2(...p)),[])){const ps=t.map(i=>poly[i]);if((ps[1][0]-ps[0][0])*(ps[2][1]-ps[0][1])-(ps[1][1]-ps[0][1])*(ps[2][0]-ps[0][0])>0)[ps[1],ps[2]]=[ps[2],ps[1]];this.tri(...ps.map(p=>[p[0],y,p[1]]),color,ps.map(p=>[p[0]/scale,p[1]/scale]),[0,1,0]);}}
 line(a,b,w,y,color,scale=4){const dx=b[0]-a[0],dz=b[1]-a[1],l=Math.hypot(dx,dz);if(l<.02)return;const x=-dz/l*w/2,z=dx/l*w/2;this.quad([a[0]+x,y,a[1]+z],[b[0]+x,y,b[1]+z],[b[0]-x,y,b[1]-z],[a[0]-x,y,a[1]-z],color,[[0,0],[l/scale,0],[l/scale,w/scale],[0,w/scale]],[0,1,0]);}
 box(x,y,z,w,h,d,color){const a=x-w/2,b=x+w/2,c=z-d/2,e=z+d/2,f=y+h;this.quad([a,y,c],[b,y,c],[b,f,c],[a,f,c],color,undefined,[0,0,-1]);this.quad([b,y,e],[a,y,e],[a,f,e],[b,f,e],color,undefined,[0,0,1]);this.quad([a,y,e],[a,y,c],[a,f,c],[a,f,e],color,undefined,[-1,0,0]);this.quad([b,y,c],[b,y,e],[b,f,e],[b,f,c],color,undefined,[1,0,0]);this.quad([a,f,c],[b,f,c],[b,f,e],[a,f,e],color,undefined,[0,1,0]);}
 mesh(material){if(!this.p.length)return null;const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(this.p,3));g.setAttribute('normal',new T.Float32BufferAttribute(this.n,3));g.setAttribute('uv',new T.Float32BufferAttribute(this.uv,2));g.setAttribute('color',new T.Float32BufferAttribute(this.c,3));g.computeBoundingSphere();const m=new T.Mesh(g,material);m.castShadow=true;m.receiveShadow=true;return m;}
}
function facade(image,style){const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const ctx=canvas.getContext('2d');ctx.fillStyle=['#dbd8cf','#c9cbc9','#b9b0a0','#c2cad0'][style];ctx.fillRect(0,0,512,512);if(image){ctx.globalAlpha=.43;ctx.drawImage(image,0,0,512,512);ctx.globalAlpha=1;}
 const r=rng(900+style);for(let i=0;i<4500;i++){ctx.fillStyle=`rgba(55,52,46,${r()*.11})`;ctx.fillRect(r()*512,r()*512,1+r()*3,1+r()*5);}
 ctx.fillStyle='rgba(33,35,31,.18)';ctx.fillRect(0,493,512,4);ctx.fillStyle='rgba(255,255,248,.45)';ctx.fillRect(0,497,512,3);
 const x=style===3?30:90,y=105,w=style===3?452:310,h=236;ctx.fillStyle='rgba(22,25,21,.22)';ctx.fillRect(x-8,y-8,w+21,h+23);ctx.fillStyle='#687270';ctx.fillRect(x-4,y-4,w+8,h+8);const grad=ctx.createLinearGradient(x,y,x+w,y+h);grad.addColorStop(0,'#233941');grad.addColorStop(.44,'#557277');grad.addColorStop(.48,'#31494f');grad.addColorStop(1,'#1e343a');ctx.fillStyle=grad;ctx.fillRect(x,y,w,h);ctx.fillStyle='rgba(194,208,196,.16)';ctx.fillRect(x+18,y+10,w*.27,h-20);ctx.fillStyle='#b8bdb6';ctx.fillRect(x+w/2-3,y,6,h);ctx.fillRect(x,y+h*.6,w,3);ctx.fillStyle='#e2e0d6';ctx.fillRect(x-8,y+h+5,w+16,10);ctx.fillStyle='rgba(0,0,0,.13)';ctx.fillRect(x-8,y+h+16,w+16,8);
 if(style===2){ctx.fillStyle='rgba(255,252,237,.34)';for(let j=y+16;j<y+h-10;j+=11)ctx.fillRect(x+5,j,w*.43,3);}
 const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=4;return texture;
}
const waterVertex=`varying vec3 vWorld;void main(){vWorld=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(vWorld,1.);}`;
const waterFragment=`precision highp float;varying vec3 vWorld;uniform float uTime;uniform vec3 uSun;uniform vec3 uEye;uniform vec3 uColor;uniform vec3 uSky;uniform float uNight;void main(){vec2 p=vWorld.xz;float t=uTime;vec3 n=normalize(vec3(sin(p.x*.075+t*.35)*.18+sin(p.y*.19-t*.27)*.09,1.,cos(p.y*.061+t*.26)*.20+sin(p.x*.16+p.y*.10+t*.6)*.06));vec3 v=normalize(uEye-vWorld);float f=pow(1.-max(dot(n,v),0.),3.);float sun=pow(max(dot(reflect(-normalize(uSun),n),v),0.),120.);vec3 c=mix(uColor,uSky,f*.75);c+=vec3(1.,.82,.56)*sun*mix(1.4,.06,uNight);float fog=1.-exp(-length(uEye-vWorld)*.000026);gl_FragColor=vec4(mix(c,uSky,fog),1.);}`;
class WorldRenderer{
 constructor(canvas,map,places,graph){if(map.mode!=='osm')throw Error('실제 OSM 원본이 없어 이 버전은 실행하지 않습니다.');this.canvas=canvas;this.map=map;this.places=places;this.graph=graph;this.width=1;this.height=1;this.yaw=.16;this.pitch=.62;this.distance=630;this.target=[-280,0,-80];this.eye=[0,0,0];this.buildCount=0;this.gpuLost=false;this.onLost=null;this._night=false;this.preset='day';this.frames=0;this.textureReady=0;this.textureFailed=[];this.coast=map.coast.map(p=>geo(...p));this.mobile=matchMedia('(max-width:680px)').matches;this.highQuality=!this.mobile;this._shadowPosition=[Infinity,Infinity,0];
 this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.gl=this.renderer.getContext();this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;this.renderer.shadowMap.enabled=this.highQuality;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.shadowMap.autoUpdate=false;this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(50,1,.3,65000);this.scene.fog=new T.FogExp2('#b7d1dd',.00014);
 this.world=new T.Group();this.scene.add(this.world);this.hemisphere=new T.HemisphereLight('#c5e4ff','#7a7566',2);this.scene.add(this.hemisphere);this.sun=new T.DirectionalLight('#fff2d8',3.3);this.sun.castShadow=true;this.sun.shadow.mapSize.set(this.mobile?1024:2048,this.mobile?1024:2048);this.sun.shadow.bias=-.00008;this.sun.shadow.normalBias=.35;this.sun.shadow.camera.near=1;this.sun.shadow.camera.far=6500;this.scene.add(this.sun,this.sun.target);
 this.sky=new root.JejuSky();this.sky.scale.setScalar(45000);this.scene.add(this.sky);this.sky.material.uniforms.turbidity.value=4;this.sky.material.uniforms.rayleigh.value=1.45;this.sky.material.uniforms.mieCoefficient.value=.006;this.sky.material.uniforms.mieDirectionalG.value=.8;
 this.materials={};this.makeMaterials();this.buildWorld();this.makeAvatar();this.setLighting('day');this.installControls();canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.gpuLost=true;this.onLost?.();});canvas.addEventListener('webglcontextrestored',()=>location.reload());
 const self=this;root.__JEJU_REALISM__={get status(){return{version:'2.0.0-realism-beta',renderer:'Three.js r180 / PBR',mapMode:self.map.mode,roads:self.map.roads.length,buildings:self.buildCount,sourceBuildings:self.map.buildings.length,coast:self.map.coastSource,photoTexturesLoaded:self.textureReady,photoTextureErrors:[...self.textureFailed],frames:self.frames,drawCalls:self.renderer.info.render.calls,triangles:self.renderer.info.render.triangles,preset:self.preset,shadows:self.renderer.shadowMap.enabled,quality:self.highQuality?'high':'light',streetViewPhotography:false,satelliteImagery:false,facadesSurveyed:false,positions:map.bounds,trees:self.treeCount||0};}};
 }
 get night(){return this._night;}set night(value){this.setLighting(value?'blue':'day');}
 makeMaterials(){const loader=new T.TextureLoader();const assetRoot=new URL('./realism/assets/',location.href).href;const metadata=root.JEJU_MATERIALS||[];
 const load=(alias,channel,onload)=>{const file=metadata.find(t=>t.alias===alias&&t.channel===channel)?.file;if(!file){this.textureFailed.push(alias+'-'+channel+' missing');return null;}const tex=loader.load(assetRoot+file,t=>{this.textureReady++;onload?.(t);this.renderer.shadowMap.needsUpdate=true;this.refreshStatus();},undefined,()=>{this.textureFailed.push(file);this.refreshStatus();});tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());if(channel==='color')tex.colorSpace=T.SRGBColorSpace;return tex;};
 const road=load('road','color'),roadNormal=load('road','normal'),wall=load('wall','color',t=>{for(let i=0;i<4;i++){const old=this.materials['facade'+i].map;this.materials['facade'+i].map=facade(t.image,i);this.materials['facade'+i].needsUpdate=true;old.dispose();}}),wallNormal=load('wall','normal'),paving=load('paving','color'),pavingNormal=load('paving','normal');
 this.materials.road=new T.MeshStandardMaterial({map:road,normalMap:roadNormal,normalScale:new T.Vector2(.48,.48),roughness:.92,vertexColors:true,side:T.DoubleSide});this.materials.paving=new T.MeshStandardMaterial({map:paving,normalMap:pavingNormal,normalScale:new T.Vector2(.42,.42),roughness:.96,vertexColors:true,side:T.DoubleSide});this.materials.ground=new T.MeshStandardMaterial({map:paving,roughness:1,vertexColors:true,side:T.DoubleSide});
 this.materials.roof=new T.MeshStandardMaterial({map:wall,normalMap:wallNormal,normalScale:new T.Vector2(.22,.22),roughness:.87,vertexColors:true,side:T.DoubleSide});this.materials.detail=new T.MeshStandardMaterial({roughness:.73,vertexColors:true});this.materials.paint=new T.MeshStandardMaterial({roughness:.75,vertexColors:true,side:T.DoubleSide});
 for(let i=0;i<4;i++)this.materials['facade'+i]=new T.MeshStandardMaterial({map:facade(null,i),roughness:.68,metalness:.03,vertexColors:true,side:T.DoubleSide});
 this.materials.water=new T.ShaderMaterial({vertexShader:waterVertex,fragmentShader:waterFragment,uniforms:{uTime:{value:0},uSun:{value:V(-.5,1,.5)},uEye:{value:V(0,50,0)},uColor:{value:col('#267482')},uSky:{value:col('#b5d3e1')},uNight:{value:0}},side:T.DoubleSide});this.materials.route=new T.MeshBasicMaterial({color:'#dcfa89',side:T.DoubleSide,depthWrite:false,transparent:true,opacity:.88});
 }
 addBatch(batch,material,group=this.world){const mesh=batch.mesh(material);if(mesh)group.add(mesh);return mesh;}
 buildWorld(){this.world.traverse(o=>{o.geometry?.dispose();});this.world.clear();this.buildCount=0;this.colliders=[];this.buildTiles=[];const chunks=new Map();const chunk=(x,z,key)=>{const a=Math.floor(x/300),b=Math.floor(z/300),id=a+','+b;if(!chunks.has(id))chunks.set(id,{x:a*300+150,z:b*300+150,batches:{}});const v=chunks.get(id);return v.batches[key]||(v.batches[key]=new Batch());};
 const b=C.bounds,left=geo(b[0],b[1])[0],right=geo(b[2],b[1])[0],south=geo(b[0],b[1])[1];const ground=new Batch();ground.flat([...this.coast,[right,south],[left,south]],0,'#b7b4a4',35);this.addBatch(ground,this.materials.ground);const sea=new Batch();sea.flat([[-45000,-45000],[45000,-45000],[45000,45000],[-45000,45000]],-.45,'#ffffff');const sm=this.addBatch(sea,this.materials.water);if(sm){sm.castShadow=false;sm.receiveShadow=false;}
 const treePositions=[];let generated=0;for(const area of this.map.areas||[]){const poly=area.coords.map(p=>geo(...p));if(poly.length<3)continue;const batch=new Batch();batch.flat(poly,.06,area.kind==='water'?'#ffffff':area.kind==='park'?'#5f774b':area.kind==='airport'?'#758361':'#b4b1a8',area.kind==='park'?18:12);this.addBatch(batch,area.kind==='water'?this.materials.water:this.materials.ground);if(area.kind==='park'){const xs=poly.map(p=>p[0]),zs=poly.map(p=>p[1]),x0=Math.min(...xs),x1=Math.max(...xs),z0=Math.min(...zs),z1=Math.max(...zs),r=rng(hash(area.id||'park'));const trials=Math.min(450,Math.ceil((x1-x0)*(z1-z0)/90));for(let i=0;i<trials&&generated<2200;i++){const p=[x0+r()*(x1-x0),z0+r()*(z1-z0)];if(!pointInPolygon(p,poly))continue;const road=this.graph.nearest(p,18);if(road&&road.distance<road.edge.width/2+4)continue;treePositions.push({p,s:.75+r()*.8,seed:hash(area.id+i)});generated++;}}}
 for(const r of this.map.roads){if(r.tunnel)continue;const p=r.coords.map(q=>geo(...q));const path=['footway','pedestrian','path','steps','cycleway'].includes(r.highway);const runway=['runway','taxiway'].includes(r.highway);let w=r.width||8;for(let i=1;i<p.length;i++){const a=p[i-1],b=p[i],len=dist(a,b);if(len<.1)continue;const x=(a[0]+b[0])/2,z=(a[1]+b[1])/2;const curb=chunk(x,z,'paving'),road=chunk(x,z,path?'paving':'road'),paint=chunk(x,z,'paint');if(!runway&&!path)curb.line(a,b,w+1.5,.11,'#c9c6bd',3);road.line(a,b,w,path?.15:.16,path?'#c9c7bb':'#a9aaa8',4);if(w>12&&!runway){const dx=(b[0]-a[0])/len,dz=(b[1]-a[1])/len;for(const offset of[-.16,.16])paint.line([a[0]-dz*offset,a[1]+dx*offset],[b[0]-dz*offset,b[1]+dx*offset],.10,.182,'#e8c06a');if(w>17)for(let t=2;t<len-5;t+=11){const q=[a[0]+dx*t,a[1]+dz*t],e=[a[0]+dx*(t+5),a[1]+dz*(t+5)];for(const side of[-1,1])paint.line([q[0]-dz*w*.27*side,q[1]+dx*w*.27*side],[e[0]-dz*w*.27*side,e[1]+dx*w*.27*side],.12,.185,'#e4e2d5');}}}}
 for(const point of this.map.points||[]){const p=geo(point.lon,point.lat);if(point.kind==='tree')treePositions.push({p,s:.8+rng(point.id)()*.8,seed:point.id});else if(point.kind==='crossing'){const n=this.graph.nearest(p,22);if(!n||n.edge.width<6||n.distance>12)continue;const e=n.edge,l=e.length,dx=(e.b[0]-e.a[0])/l,dz=(e.b[1]-e.a[1])/l,w=Math.min(e.width-1.4,20),b=chunk(p[0],p[1],'paint');for(let offset=-w/2;offset<w/2;offset+=1.15){const center=[n.point[0]-dz*offset,n.point[1]+dx*offset];b.line([center[0]-dx*1.8,center[1]-dz*1.8],[center[0]+dx*1.8,center[1]+dz*1.8],.55,.19,'#edece4');}}}
 for(const building of this.map.buildings){let p=building.coords.map(q=>geo(...q));if(p.length>1&&dist(p[0],p.at(-1))<.01)p.pop();if(p.length<3||p.length>5000)continue;const xs=p.map(q=>q[0]),zs=p.map(q=>q[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),cx=(minX+maxX)/2,cz=(minZ+maxZ)/2;let h=building.height||9;let area=0;for(let i=0;i<p.length;i++)area+=p[i][0]*p[(i+1)%p.length][1]-p[(i+1)%p.length][0]*p[i][1];if(area>0)p.reverse();const id=hash(building.id),r=rng(id),style=h>32?3:id%3,wall=chunk(cx,cz,'facade'+style),roof=chunk(cx,cz,'roof'),detail=chunk(cx,cz,'detail');const color=/^#[0-9a-f]{6}$/i.test(building.wallColor||'')?building.wallColor:palettes[id%palettes.length];const rc=/^#[0-9a-f]{6}$/i.test(building.roofColor||'')?building.roofColor:['#a6aaa2','#7b978e','#b2b2a8','#819793','#9e9a8c'][id%5];roof.flat(p,h+.14,rc,5);for(let i=0;i<p.length;i++){const a=p[i],b=p[(i+1)%p.length],len=dist(a,b);if(len<.1)continue;const n=[-(b[1]-a[1])/len,0,(b[0]-a[0])/len];wall.quad([a[0],.12,a[1]],[b[0],.12,b[1]],[b[0],h,b[1]],[a[0],h,a[1]],color,[[0,0],[len/3.8,0],[len/3.8,h/3.2],[0,h/3.2]],n);detail.line(a,b,.24,h+.28,'#cccbc3',1);}
 if(h>6&&maxX-minX>8&&maxZ-minZ>8&&pointInPolygon([cx,cz],p)&&r()>.45){detail.box(cx,h+.14,cz,1.5,.7,1.1,'#cacdc6');detail.box(cx,h+.85,cz,.9,.06,.7,'#697874');}
 this.colliders.push({x:cx,z:cz,poly:p,min:[minX,0,minZ],max:[maxX,h,maxZ]});this.buildCount++;}
 for(const c of chunks.values()){const group=new T.Group();for(const [key,batch]of Object.entries(c.batches)){const mesh=this.addBatch(batch,this.materials[key],group);if(mesh&&['paint','road','paving'].includes(key))mesh.castShadow=false;}this.world.add(group);this.buildTiles.push({x:c.x,z:c.z,group});}
 this.makeTrees(treePositions.slice(0,3200));this.setRoute([]);this.renderer.shadowMap.needsUpdate=true;
 }
 makeTrees(trees){this.treeCount=trees.length;if(!trees.length)return;const trunk=new T.InstancedMesh(new T.CylinderGeometry(.15,.27,3.3,7),new T.MeshStandardMaterial({color:'#6a5b47',roughness:1}),trees.length),leaves=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),new T.MeshStandardMaterial({color:'#83986d',roughness:1}),trees.length*3);const dummy=new T.Object3D();let i=0;for(const t of trees){const r=rng(t.seed),s=t.s;dummy.position.set(t.p[0],1.65*s,t.p[1]);dummy.scale.set(s,s,s);dummy.rotation.set(0,0,0);dummy.updateMatrix();trunk.setMatrixAt(i/3,dummy.matrix);for(let j=0;j<3;j++){dummy.position.set(t.p[0]+(r()-.5)*2*s,(4+j*.85)*s,t.p[1]+(r()-.5)*2*s);dummy.scale.set((1.7+r())*s,(1.6+r())*s,(1.7+r())*s);dummy.rotation.set(r(),r()*6,r());dummy.updateMatrix();leaves.setMatrixAt(i,dummy.matrix);leaves.setColorAt(i,col(['#799560','#587e4e','#6e8b55','#94a773'][Math.floor(r()*4)]));i++;}}trunk.castShadow=leaves.castShadow=true;trunk.receiveShadow=leaves.receiveShadow=true;this.world.add(trunk,leaves);}
 makeAvatar(){this.avatar=new T.Group();this.scene.add(this.avatar);const mats={shirt:new T.MeshStandardMaterial({color:'#f29163',roughness:.9}),skin:new T.MeshStandardMaterial({color:'#d4a77d',roughness:.8}),pants:new T.MeshStandardMaterial({color:'#253b47',roughness:.9}),shoe:new T.MeshStandardMaterial({color:'#efeadc',roughness:.8}),hair:new T.MeshStandardMaterial({color:'#2b2a27',roughness:.95}),bag:new T.MeshStandardMaterial({color:'#c6b692',roughness:.95})};this.avatarMaterials=mats;const mesh=(g,m,x,y,z,parent=this.avatar)=>{const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;};mesh(new T.CapsuleGeometry(.29,.39,4,10),mats.shirt,0,1.19,0);mesh(new T.SphereGeometry(.215,14,10),mats.skin,0,1.83,0);mesh(new T.SphereGeometry(.223,14,10,0,Math.PI*2,0,Math.PI*.53),mats.hair,0,1.84,0);mesh(new T.BoxGeometry(.40,.46,.19),mats.bag,0,1.23,-.28);this.arms=[];this.legs=[];for(const sign of[-1,1]){const arm=new T.Group();arm.position.set(sign*.36,1.4,0);this.avatar.add(arm);mesh(new T.CapsuleGeometry(.082,.43,3,8),mats.skin,0,-.25,0,arm);this.arms.push(arm);const leg=new T.Group();leg.position.set(sign*.15,.89,0);this.avatar.add(leg);mesh(new T.CapsuleGeometry(.103,.51,3,8),mats.pants,0,-.30,0,leg);mesh(new T.BoxGeometry(.22,.13,.35),mats.shoe,0,-.70,.05,leg);this.legs.push(leg);}const ring=new T.Mesh(new T.RingGeometry(.9,1.02,40),new T.MeshBasicMaterial({color:'#dcfa89',side:T.DoubleSide,transparent:true,opacity:.75}));ring.rotation.x=-Math.PI/2;ring.position.y=.2;this.avatar.add(ring);}
 setRoute(points){if(this.route){this.scene.remove(this.route);this.route.geometry.dispose();}const b=new Batch();for(let i=1;i<points.length;i++)b.line(points[i-1],points[i],2.2,.36,'#ffffff');this.route=b.mesh(this.materials.route);if(this.route){this.route.castShadow=false;this.route.receiveShadow=false;this.scene.add(this.route);}}
 setLighting(preset){this.preset=preset;this._night=preset==='blue';const p={day:{sun:[-.52,.85,.37],light:'#fff4dc',power:3.0,hemi:1.7,fog:'#b6ccda',density:.00011,exposure:1.1},golden:{sun:[-.85,.29,.25],light:'#ffd199',power:3.5,hemi:1.2,fog:'#cfc6b5',density:.00016,exposure:1.16},blue:{sun:[-.4,.08,.85],light:'#afc7fa',power:.35,hemi:1.0,fog:'#1b334b',density:.00019,exposure:1.0}}[preset]||null;if(!p)return;this.lightConfig=p;this.sun.color.set(p.light);this.sun.intensity=p.power;this.hemisphere.intensity=p.hemi;this.scene.fog.color.set(p.fog);this.scene.fog.density=p.density;this.renderer.toneMappingExposure=p.exposure;this.sky.material.uniforms.sunPosition.value.set(...p.sun);this.sky.material.uniforms.turbidity.value=preset==='golden'?6:3.8;this.sky.material.uniforms.rayleigh.value=preset==='blue'?3:1.45;this.materials.water.uniforms.uSun.value.set(...p.sun);this.materials.water.uniforms.uNight.value=this._night?1:0;this.materials.water.uniforms.uSky.value.set(p.fog);this.materials.water.uniforms.uColor.value.set(this._night?'#0d2536':'#206374');for(let i=0;i<4;i++){this.materials['facade'+i].emissive.set(this._night?'#283649':'#000000');this.materials['facade'+i].emissiveIntensity=.2;}this._shadowPosition=[Infinity,Infinity,0];this.renderer.shadowMap.needsUpdate=true;this.refreshStatus();}
 installControls(){document.querySelectorAll('[data-light]').forEach(b=>b.addEventListener('click',()=>{this.setLighting(b.dataset.light);document.body.classList.toggle('night',this.night);}));document.querySelector('#real-quality')?.addEventListener('click',()=>{this.highQuality=!this.highQuality;this.renderer.shadowMap.enabled=this.highQuality;this.renderer.shadowMap.needsUpdate=true;this.refreshStatus();});document.querySelector('#real-cinema')?.addEventListener('click',()=>{document.body.classList.toggle('cinema');setTimeout(()=>this.resize(),80);});this.refreshStatus();}
 refreshStatus(){document.querySelectorAll('[data-light]').forEach(b=>{b.classList.toggle('active',b.dataset.light===this.preset);b.setAttribute('aria-pressed',String(b.dataset.light===this.preset));});const q=document.querySelector('#real-quality');if(q)q.textContent=this.highQuality?'고화질':'가벼운 모드';const s=document.querySelector('#real-status');if(s)s.textContent=`OSM ${this.map.buildings.length.toLocaleString()}개 건물 · 재질·외관 연출`;}
 resize(){const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,this.highQuality?1.5:1);if(rect.width<1||rect.height<1)return;if(this.width!==rect.width||this.height!==rect.height||this._dpr!==dpr){this.width=rect.width;this.height=rect.height;this._dpr=dpr;this.renderer.setPixelRatio(dpr);this.renderer.setSize(rect.width,rect.height,false);this.camera.aspect=rect.width/rect.height;this.camera.updateProjectionMatrix();}}
 draw(player,phase,moving){if(this.gpuLost)return;this.resize();this.frames++;const d=this.distance,p=clamp(this.pitch,.17,1.52);this.eye=[this.target[0]+Math.sin(this.yaw)*Math.cos(p)*d,this.target[1]+Math.sin(p)*d,this.target[2]+Math.cos(this.yaw)*Math.cos(p)*d];
 if(d<100){const delta=this.eye.map((v,i)=>v-this.target[i]);let firstHit=1,obstacleTop=0;for(const c of this.colliders){if(Math.abs(c.x-this.target[0])>150||Math.abs(c.z-this.target[2])>150)continue;if(pointInPolygon([this.target[0],this.target[2]],c.poly))continue;for(let t=1.5/d;t<firstHit;t+=.5/d){const x=this.target[0]+delta[0]*t,z=this.target[2]+delta[2]*t,y=this.target[1]+delta[1]*t;if(y>c.max[1]+.5||x<c.min[0]||x>c.max[0]||z<c.min[2]||z>c.max[2])continue;if(pointInPolygon([x,z],c.poly)){firstHit=t;obstacleTop=c.max[1];break;}}}if(firstHit<1){if(firstHit*d>=6){const f=firstHit-.04;this.eye=this.target.map((v,i)=>v+delta[i]*f);}else this.eye[1]=Math.max(this.eye[1],obstacleTop+2.5);}}
 this.camera.position.set(...this.eye);this.camera.near=clamp(d*.002,.1,80);this.camera.updateProjectionMatrix();this.camera.lookAt(...this.target);this.camera.updateMatrixWorld();this.avatar.position.set(player.pos[0],.18,player.pos[1]);this.avatar.rotation.y=player.heading||0;const s=d>140?Math.min(5,d/140):1;this.avatar.scale.setScalar(s);this.avatarMaterials.shirt.color.set(player.color);const swing=moving?Math.sin(phase*10)*.55:0;this.legs[0].rotation.x=swing;this.legs[1].rotation.x=-swing;this.arms[0].rotation.x=-swing*.85;this.arms[1].rotation.x=swing*.85;
 const local=d<180,radius=local?1600:Math.max(2300,d*1.7);for(const t of this.buildTiles)t.group.visible=Math.hypot(t.x-this.target[0],t.z-this.target[2])<radius;const span=clamp(d*1.2,160,2100);if(Math.hypot(this.target[0]-this._shadowPosition[0],this.target[2]-this._shadowPosition[1])>4||Math.abs(span-this._shadowPosition[2])>3){const p=this.lightConfig?.sun||[-.5,1,.4],scale=2800;this.sun.position.set(this.target[0]+p[0]*scale,Math.max(160,p[1]*scale),this.target[2]+p[2]*scale);this.sun.target.position.set(this.target[0],0,this.target[2]);const c=this.sun.shadow.camera;c.left=c.bottom=-span;c.right=c.top=span;c.updateProjectionMatrix();this._shadowPosition=[this.target[0],this.target[2],span];this.renderer.shadowMap.needsUpdate=true;}
 if(moving&&this.frames%4===0)this.renderer.shadowMap.needsUpdate=true;this.materials.water.uniforms.uTime.value=performance.now()/1000;this.materials.water.uniforms.uEye.value.set(...this.eye);this.renderer.render(this.scene,this.camera);
 }
 project(x,y,z){if(!this.camera)return null;const p=V(x,y,z).project(this.camera);return{x:(p.x*.5+.5)*this.width,y:(-.5*p.y+.5)*this.height,z:p.z,visible:p.z<1&&p.z>-1&&Math.abs(p.x)<1.05&&Math.abs(p.y)<1.1};}
 focus(position,distance){this.target=[position[0],0,position[1]];if(distance!=null)this.distance=distance;}
}
root.JejuRender={WorldRenderer};
})(globalThis);
