import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';import {prepareVisitorConfig} from './publish-public-config.mjs';
const repo='kokoom94-ai/jeju-oldtown-3d',key='TEST-ONLY-PUBLISHER-FIXTURE-00000';
const env={GITHUB_REPOSITORY:repo,PUBLIC_KEY_VISIBILITY_ACCEPTED:'true',VWORLD_PUBLIC_KEY:key};
async function fixture(fn,meta={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'public-config-test-'));try{await fs.writeFile(path.join(dir,'site.json'),JSON.stringify({repository:repo,version:'3.8.0-visitor-navigation',...meta}));await fs.writeFile(path.join(dir,'integrity.json'),JSON.stringify({repository:repo,files:[{path:'site.json'},{path:'public-connection.json'}]}));await fs.writeFile(path.join(dir,'public-connection.json'),'{"enabled":false}');await fn(dir);}finally{await fs.rm(dir,{recursive:true,force:true});}}
test('artifact key enables visitors, never returned in result or truth certification',()=>fixture(async dir=>{const result=await prepareVisitorConfig(dir,env),cfg=JSON.parse(await fs.readFile(path.join(dir,'public-connection.json'))),meta=JSON.parse(await fs.readFile(path.join(dir,'site.json')));assert.equal(cfg.apiKey,key);assert.equal(cfg.enabled,true);assert.equal(cfg.imagery,false);assert(!JSON.stringify(result).includes(key));assert.equal(meta.productionReady,false);assert.equal(meta.sdkLiveTested,false);}));
test('manifest is updated for exactly the two changed public files',()=>fixture(async dir=>{await prepareVisitorConfig(dir,env);const manifest=JSON.parse(await fs.readFile(path.join(dir,'integrity.json')));for(const e of manifest.files){const b=await fs.readFile(path.join(dir,e.path));assert.equal(e.bytes,b.length);assert.equal(e.sha256,createHash('sha256').update(b).digest('hex'));}}));
test('missing key does not publish a disabled replacement',()=>fixture(async dir=>{await assert.rejects(()=>prepareVisitorConfig(dir,{...env,VWORLD_PUBLIC_KEY:''}),/VWORLD_PUBLIC_KEY_REQUIRED/);assert.equal(await fs.readFile(path.join(dir,'public-connection.json'),'utf8'),'{"enabled":false}');}));
test('other repository is refused',()=>fixture(async dir=>{await assert.rejects(()=>prepareVisitorConfig(dir,{...env,GITHUB_REPOSITORY:'kokoom94-ai/jeju-now-981'}),/PUBLISHER_NOT_AUTHORIZED/);}));
test('older untested site is refused',()=>fixture(async dir=>{await assert.rejects(()=>prepareVisitorConfig(dir,env),/PUBLISHER_WRONG_SITE/);},{version:'3.7.1-sdk-diagnostics'}));
test('optional imagery must be explicit',()=>fixture(async dir=>{await prepareVisitorConfig(dir,{...env,VWORLD_USE_IMAGERY:'true'});assert.equal(JSON.parse(await fs.readFile(path.join(dir,'public-connection.json'))).imagery,true);}));
